FROM node:16

LABEL version="1.0"
LABEL description="Image of MERN API"

WORKDIR /app

COPY ['package.json', 'package-lock.json','./']

RUN npm install && npm cache clean --force

COPY . .

EXPOSE 5000

CMD ["npm ","run","dev"]